Map<String, String> englishStrings = {
  'Smart Gloves':'Smart Gloves',
  'confirm':'confirm',
  'Verbs':'Verbs',
  'Emotions':'Emotions',
  'Places':'Places',
  'Questions':'Questions',
  'Me':'Me',
  'Welcome word':'Welcome word',
  'Dark Mode':'Dark Mode',
  'English':'English',
  'home': 'اhome',
  'chat': 'chat',
  'dictionary': 'dictionary',
  'Play':'Play',
  'welcomeBack': 'Welcome Back',
  'enterCredentials': 'Enter your credentials to login',
  'email': 'Email',
  'password': 'Password',
  'login': 'Login',
  'guest': 'Guest',
  'noAccount': "Don't have an account?",
  'signUp': 'Sign Up',
  'welcome': 'Welcome',
  'loggedIn': 'You have logged in.',
  'sorry': 'Sorry',
  'incorrectEmailPassword': 'The email or password is incorrect.',
  'error': 'Error',
  'userDataNotFound': 'User data not found.',
  'createAccount': 'Create Account',
  'enterDetails': 'Enter your details to sign up',
  'name': 'Name',
  'congratulations': 'Congratulations',
  'signedUp': 'You have signed up.',
  'passwordEmailValidation': 'Please enter a password with at least 8 characters and a valid email.',
  'enterAllFields': 'Please enter all fields.',
  'haveAccount': 'Already have an account?',
  // Add more translations here
};