// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBo8XH-DcAWU72eM81t4vi4gFd7JMejA',
    appId: '1:446279012895:web:a7d597f3d4fa1445813b2a',
    messagingSenderId: '446279012895',
    projectId: 'gproject-cbcd2',
    authDomain: 'gproject-cbcd2.firebaseapp.com',
    databaseURL: 'https://gproject-cbcd2-default-rtdb.firebaseio.com',
    storageBucket: 'gproject-cbcd2.appspot.com',
    measurementId: 'G-91NRSW7ECR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRHY7V0ZEvbdQ338JFFcaZGnl-osYpSo',
    appId: '1:446279012895:android:cc2df180ae478220813b2a',
    messagingSenderId: '446279012895',
    projectId: 'gproject-cbcd2',
    databaseURL: 'https://gproject-cbcd2-default-rtdb.firebaseio.com',
    storageBucket: 'gproject-cbcd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhypsNY6dkc4vJoMGEQAaB6xRy-C-Qb4',
    appId: '1:446279012895:ios:29f3dc64cbc0087d813b2a',
    messagingSenderId: '446279012895',
    projectId: 'gproject-cbcd2',
    databaseURL: 'https://gproject-cbcd2-default-rtdb.firebaseio.com',
    storageBucket: 'gproject-cbcd2.appspot.com',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLBo8XH-DcAWU72eM81t4vi4gFd7JMejA',
    appId: '1:446279012895:web:68277304381136f7813b2a',
    messagingSenderId: '446279012895',
    projectId: 'gproject-cbcd2',
    authDomain: 'gproject-cbcd2.firebaseapp.com',
    databaseURL: 'https://gproject-cbcd2-default-rtdb.firebaseio.com',
    storageBucket: 'gproject-cbcd2.appspot.com',
    measurementId: 'G-VZ2VEWT1L7',
  );
}
